name: diploma_frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  routemaster: ^1.0.1
  provider: ^6.0.5
  easy_localization: ^3.0.1
  shared_preferences: ^2.1.0
  http: ^0.13.5
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/language/
    - assets/language/en-US.json
    - assets/language/uk-UA.json
    - assets/images/
    - assets/images/ukraine-flag-icon.svg
    - assets/images/england-flag-icon.svg

  fonts:
    - family: InknutAntiqua
      fonts:
        - asset: assets/fonts/InknutAntiqua-Bold.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
